(defvar *global-count* 0)
(defun counted-compare (x y)
  (setq *global-count* (+ *global-count* 1))
  (<= x y)
)
(defun sortmerge (a b &optional (compare-form #'counted-compare))
  (if (and a b)
    (let ((x (first a)) (y (first b)))
      (if (and (atom x) (atom y))
        (if (funcall compare-form x y)
          (append (list x) (sortmerge (rest a) b))
          (append (list y) (sortmerge a (rest b)))
        )
        (if (atom x)
          (sortmerge (list x) (sortmerge (rest a) b))
          (sortmerge (list y) (sortmerge a (rest b)))
        )
      )
    )
    (let ((x (or a b)))
      (if (and x (rest x))
        (sortmerge (list (first x)) (rest x))
        (if (atom (first x))
          x
          (mergesort (first x))
        )
      )
    )
  )
)
(defun mergesort (l)
  (if (< (length l) 3)
    (sortmerge (if (first l) (list (first l))) (if (second l) (list (second l))))
    (let ((left 'nil)(right 'nil))
      (progn
        (dotimes (i (ceiling (/ (length l) 2)) 't)
          (setq left (append left (list (nth i l))))
        )
        (dotimes (i (floor (/ (length l) 2)) 't)
          (setq right (append right (list (nth (+ (ceiling (/ (length l) 2)) i) l))))
        )
        (sortmerge (mergesort left) (mergesort right))
      )
    )
  )
)
(defun generate-random-list-of-lists (&optional (n 100))
  (let ((l 'nil))
    (dotimes (i n l)
      (if (eq (random 10) 0)
        (setq l (append l (list (generate-random-list-of-lists (+ 2 (random (ceiling (/ n 10))))))))
        (setq l (append l (list (random (* n 10)))))
      )
    )
  )
)
(defun sorted (l)
  (if (> (length l) 1)
    (and (<= (first l) (second l)) (sorted (rest l)))
    't
  )
)
